/* 
 +--------------------------------------------------------------+
 |                                                              |
 |           LENSCALC (Contact Lens Design Program)             |
 |              (c)opyright 1988 James J. Carter                |
 |                   All Rights Reserved.                       |
 |                                                              |
 +--------------------------------------------------------------+
*/
extern int input_table[];

#define NO_OP        0
#define MOD_CT       1
#define MOD_ET       2
#define MOD_POWER    3
#define MOD_INDEX    4
#define MOD_MATERIAL 40
#define MOD_BASE     5
#define MAKE_LENTIC  10
#define MAKE_PRINT   11
#define PRINT_TO_FILE 12
#define NEW_LENS     20
#define MOD_JUNCT    6
#define PRISM_OPT	30
#define SAVE_DATA       100
#define REDRAW		1000
#define PRINT_VER	1001
#define GRIPE		1010
#define BIF_MENU	2000
#define TORIC_MENU	2010
#define SPECIAL_MENU	2020

#define SHELL           -3
#define EXIT_SAVE       -2
#define EXIT_PROG       -1


